import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc

# 1. Load your dataset (assuming your output from download_data.py)
# df = pd.read_csv('btc_usd_daily.csv')

# --- SIMULATED DATA FOR DEMONSTRATION ---
np.random.seed(42)
dates = pd.date_range(start='2020-01-01', periods=1000)
df = pd.DataFrame({
    'Close': np.random.normal(40000, 2000, 1000).cumsum(),
    'Volume': np.random.normal(10000, 2000, 1000)
}, index=dates)

# 2. Feature Engineering (Lag Features)
df['Prev_Close'] = df['Close'].shift(1)
df['Lag_7'] = df['Close'].shift(7)
df['Lag_14'] = df['Close'].shift(14)
df['Prev_Volume'] = df['Volume'].shift(1)

# 3. Create the Classification Target (1 = UP, 0 = DOWN)
df['Next_Day_Close'] = df['Close'].shift(-1)
df['Target_Up'] = (df['Next_Day_Close'] > df['Close']).astype(int)

# Drop NaN values generated by shifting
df.dropna(inplace=True)

# 4. Define Features and Target
X = df[['Prev_Close', 'Lag_7', 'Lag_14', 'Prev_Volume']]
y = df['Target_Up']

# 5. Chronological Train/Test Split (80% Train, 20% Test)
split_index = int(len(df) * 0.8)
X_train, X_test = X.iloc[:split_index], X.iloc[split_index:]
y_train, y_test = y.iloc[:split_index], y.iloc[split_index:]

# 6. Train the Classification Model
model = RandomForestClassifier(n_estimators=100, random_state=42)
# model = LogisticRegression() # Alternative model
model.fit(X_train, y_train)

# 7. Predictions and Probabilities
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

# 8. Print Metrics
print("Classification Report:")
print(classification_report(y_test, y_pred))

# 9. Plotting the Graphs
fig, ax = plt.subplots(1, 2, figsize=(14, 5))

# Graph 1: Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax[0])
ax[0].set_title('Confusion Matrix: Bitcoin Price Direction')
ax[0].set_xlabel('Predicted Label (0 = Down, 1 = Up)')
ax[0].set_ylabel('True Label')

# Graph 2: ROC Curve
fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)
ax[1].plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
ax[1].plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
ax[1].set_title('Receiver Operating Characteristic (ROC)')
ax[1].set_xlabel('False Positive Rate')
ax[1].set_ylabel('True Positive Rate')
ax[1].legend(loc="lower right")

plt.tight_layout()
plt.show()
